M48
; DRILL file {KiCad 7.0.3-24-g09febce4ce} date Wed 24 May 2023 02:24:56 AM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-24T02:24:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.3-24-g09febce4ce
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X6.4024Y-1.9807
X6.4024Y-2.2083
T2
X5.1102Y-1.2913
X6.0591Y-2.374
X6.5551Y-1.6339
T0
M30
